title: Tasty Codes
email: f@tasty.codes
description: > # this means to ignore newlines until "baseurl:"
  This is an experimental blog, I will try to write about things I'm
  researching like artificial intelligence, cloud computing, machine 
  learning and IoT (internet of things), mobile development and why 
  not our usual web based development. You can read more 
  about this in the about page.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tasty.codes" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: soyfedex
github_username: federicorinaldi
facebook_username: federicorinaldi
instagram_username: fknfdx
googleplus_username: +FedericoRinaldiM
linkedin_username: federicorinaldi
paginate: 5
paginate_path: "/blog/page:num/"
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
